name:                umlaut
version:             0.1.0.0
github:              "bjornbm/umlaut"
license:             BSD3
author:              "Björn Buckwalter"
maintainer:          "bjorn@buckwalter.se"
copyright:           "2019 Björn Buckwalter"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bjornbm/umlaut#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  umlaut-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - umlaut
